### ISSUE TITLE
`pad` is not adding the correct padding

### ISSUE THREAD

**Issue by poke** [michd/js-util#1]
```
return padEnd ? (str + padEnd) : (padEnd + str);
```

`padEnd` is a boolean, so this will produce undesired results. You should consider unit-testing such utilty modules. Even more so, when you plan to use them all over the place ;)

**Comment by michd** [comment]
Good catch, I hadn't actually tested this implementation - way to go, me. I threw it together based on a simpler implementation and then neglected to test.

Thanks!
